# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
"""Build the patched upstream vLLM payload for the vllm-musa wheel."""

from __future__ import annotations

import re
import shutil
from ast import literal_eval
from dataclasses import dataclass
from pathlib import Path

BUNDLED_DISTRIBUTION = "vllm-musa"
EXPECTED_VERSION_REWRITES = 4
EXPECTED_METADATA_REWRITES = 1

_VLLM_VERSION_LOOKUP = re.compile(
    r"\b(?:importlib\.metadata\.)?version\(\s*"
    r"(?P<quote>['\"])vllm(?P=quote)\s*\)"
)
_VLLM_METADATA_LOOKUP = re.compile(
    r"(?P<prefix>\b(?:importlib\.metadata\.)?"
    r"(?:metadata|distribution)\(\s*)"
    r"(?P<quote>['\"])vllm(?P=quote)"
)
_VERSION_ASSIGNMENT = re.compile(
    r"^__version__\s*=\s*version\s*=\s*(?P<value>['\"].*?['\"])", re.MULTILINE
)


@dataclass(frozen=True)
class BundleResult:
    files: int
    version_rewrites: int
    metadata_rewrites: int


def _copy_ignore(source: Path):
    def ignore(directory: str, names: list[str]) -> set[str]:
        directory_path = Path(directory)
        ignored = {
            name
            for name in names
            if name == "__pycache__" or name.endswith((".pyc", ".pyo"))
        }
        if directory_path.resolve() == source.resolve():
            ignored.update(
                name
                for name in names
                if name.endswith(".so")
                and name.startswith(("_C.", "_C_stable_libtorch.", "_moe_C."))
            )
        return ignored

    return ignore


def _read_generated_version(package_dir: Path) -> str:
    version_module = (package_dir / "_version.py").read_text(encoding="utf-8")
    match = _VERSION_ASSIGNMENT.search(version_module)
    if match is None:
        raise RuntimeError("Generated vLLM version module has no version assignment")
    version = literal_eval(match.group("value"))
    if not isinstance(version, str):
        raise RuntimeError("Generated vLLM version is not a string")
    return version


def _rewrite_distribution_metadata(package_dir: Path) -> tuple[int, int]:
    upstream_version = _read_generated_version(package_dir)
    version_rewrites = 0
    metadata_rewrites = 0
    for path in package_dir.rglob("*.py"):
        source = path.read_text(encoding="utf-8")
        bundled, version_count = _VLLM_VERSION_LOOKUP.subn(
            repr(upstream_version), source
        )
        bundled, metadata_count = _VLLM_METADATA_LOOKUP.subn(
            rf"\g<prefix>\g<quote>{BUNDLED_DISTRIBUTION}\g<quote>", bundled
        )
        if version_count or metadata_count:
            path.write_text(bundled, encoding="utf-8")
            version_rewrites += version_count
            metadata_rewrites += metadata_count

    if version_rewrites != EXPECTED_VERSION_REWRITES:
        raise RuntimeError(
            "Unexpected number of vLLM distribution version lookups: "
            f"expected {EXPECTED_VERSION_REWRITES}, found {version_rewrites}"
        )
    if metadata_rewrites != EXPECTED_METADATA_REWRITES:
        raise RuntimeError(
            "Unexpected number of vLLM distribution metadata lookups: "
            f"expected {EXPECTED_METADATA_REWRITES}, found {metadata_rewrites}"
        )
    return version_rewrites, metadata_rewrites


def _static_version_tuple(version: str) -> tuple[int | str, ...]:
    match = re.match(r"(?P<release>\d+(?:\.\d+)*)(?P<suffix>.*)", version)
    if match is None:
        return (0, 0, version)
    release = tuple(int(part) for part in match.group("release").split("."))
    suffix = tuple(
        part
        for part in re.split(r"[.+-]", match.group("suffix"))
        if part
    )
    return (*release, *suffix)


def generate_vllm_version(
    repo: Path, fallback_version: str, commit_id: str | None
) -> str:
    """Generate vLLM's ignored version module with an archive-safe fallback."""
    version_path = repo / "vllm" / "_version.py"
    if (repo / ".git").exists():
        from setuptools_scm import get_version

        return get_version(root=str(repo), write_to="vllm/_version.py")

    version_tuple = _static_version_tuple(fallback_version)
    version_path.write_text(
        "# generated by the vllm-musa bundled-wheel build\n"
        "from __future__ import annotations\n\n"
        f"__version__ = version = {fallback_version!r}\n"
        f"__version_tuple__ = version_tuple = {version_tuple!r}\n"
        f"__commit_id__ = commit_id = {commit_id!r}\n",
        encoding="utf-8",
    )
    return fallback_version


def bundle_vllm_package(source: Path, destination: Path) -> BundleResult:
    """Copy patched vLLM into a wheel staging tree.

    The vllm-musa build owns the three C++/MUSA extensions, so stale copies of
    those files are excluded. Prebuilt Rust artifacts remain part of the
    payload when the source staging tree provides them.
    """
    if not (source / "__init__.py").is_file():
        raise RuntimeError(f"Prepared vLLM package is missing: {source}")
    if not (source / "_version.py").is_file():
        raise RuntimeError(f"Generated vLLM version module is missing: {source}")

    shutil.rmtree(destination, ignore_errors=True)
    shutil.copytree(source, destination, ignore=_copy_ignore(source))
    version_rewrites, metadata_rewrites = _rewrite_distribution_metadata(destination)
    files = sum(path.is_file() for path in destination.rglob("*"))
    return BundleResult(
        files=files,
        version_rewrites=version_rewrites,
        metadata_rewrites=metadata_rewrites,
    )
