from .car_rmsnorm import (
    CAR_RMSNORM_POLICY_TABLE,
    FUSED_ALLREDUCE_RMSNORM_MODEL_FAMILY,
    FUSED_ALLREDUCE_RMSNORM_POLICY_VERSION,
    FUSED_ALLREDUCE_RMSNORM_TARGET_HIDDEN_SIZE,
    FUSED_ALLREDUCE_RMSNORM_TP2_MIN_ROWS,
    FUSED_ALLREDUCE_RMSNORM_TP4_HIDDEN_SIZE,
    FUSED_ALLREDUCE_RMSNORM_TP4_POLICY,
    FUSED_ALLREDUCE_RMSNORM_TP4_SINGLETON_ROWS,
    can_use_fused_allreduce_rmsnorm,
    fused_allreduce_rmsnorm_compile_endpoints,
    fused_allreduce_rmsnorm_compile_reject_reason,
    fused_allreduce_rmsnorm_config_reject_reason,
    can_enable_fused_allreduce_rmsnorm,
    infer_car_rmsnorm_model_family,
)
from .qwen import (
    matches_qwen35_moe_bf16_decode_gemv_layer,
    matches_qwen35_moe_bf16_prefill_layer,
)
from .resolver import (
    bind_optimization_contract,
    prefers_optimization,
    resolve_optimization_contract,
)
from .types import (
    ExecutionSignature,
    ModelFamily,
    ModelRole,
    ModelSignature,
    MusaOptimizationContract,
    OptimizationFeature,
)

__all__ = [
    "ExecutionSignature",
    "ModelFamily",
    "ModelRole",
    "ModelSignature",
    "MusaOptimizationContract",
    "OptimizationFeature",
    "bind_optimization_contract",
    "matches_qwen35_moe_bf16_decode_gemv_layer",
    "matches_qwen35_moe_bf16_prefill_layer",
    "prefers_optimization",
    "resolve_optimization_contract",
    "FUSED_ALLREDUCE_RMSNORM_POLICY_VERSION",
    "FUSED_ALLREDUCE_RMSNORM_MODEL_FAMILY",
    "CAR_RMSNORM_POLICY_TABLE",
    "FUSED_ALLREDUCE_RMSNORM_TP2_MIN_ROWS",
    "FUSED_ALLREDUCE_RMSNORM_TP4_HIDDEN_SIZE",
    "FUSED_ALLREDUCE_RMSNORM_TP4_POLICY",
    "FUSED_ALLREDUCE_RMSNORM_TP4_SINGLETON_ROWS",
    "FUSED_ALLREDUCE_RMSNORM_TARGET_HIDDEN_SIZE",
    "can_use_fused_allreduce_rmsnorm",
    "fused_allreduce_rmsnorm_compile_endpoints",
    "fused_allreduce_rmsnorm_compile_reject_reason",
    "fused_allreduce_rmsnorm_config_reject_reason",
    "can_enable_fused_allreduce_rmsnorm",
    "infer_car_rmsnorm_model_family",
]
